eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    com:
      netflix:
        discovery:
          shared:
            resolver:
              aws:
                ConfigClusterResolver: WARN
    gateway:
      filters:
        JwtAuthFilter: INFO
    org:
      springframework:
        cloud:
          gateway:
            route:
              routedefinition-locator: INFO
    reactor:
      netty: INFO
    root: INFO

server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: forum-service
          uri: lb://forum-service
          predicates:
            - Path=/forum/**
        - id: feedback-service
          uri: lb://feedback-service
          predicates:
            - Path=/feedback/**
        - id: children-profile
          uri: lb://children-profile
          predicates:
            - Path=/children/**
        - id: image-gallery
          uri: lb://image-gallery
          predicates:
            - Path=/image/**
        - id: auth-users
          uri: lb://auth-users
          predicates:
            - Path=/auth/**
